stellar/stellar-disbursement-platform-frontend

- src/components/PageHeader/index.tsx
- src/generated/gitInfo.ts
It was decided to not use the Stellar logo in the product, since this will be hosted by others and if we were to use the Stellar logo, it could seem like we’re co-responsible for their use case, which could raise a legal problem for SDF.
> SDP-897: Remove Stellar logo from Page Header

- src/components/WalletTrustlines/index.tsx
- src/components/WalletTrustlines/styles.scss
The screen that lists the trustlines doesn't show the issuer of an asset, just its code.
You can't tell if the asset is correct just by that.
It’s a basic concept of the Stellar network that an asset consists of the pair Code:Issuer.
> SDP-895: Include trustline asset issuer

- src/generated/gitInfo.ts
This file is generated during the build process, so we don't need to have it in the repo. It's causing a lot of unnecessary merge conflicts because it changes on every commit.
> Remove generated/gitInfo.ts file from repo

- src/helpers/formatPaymentDetails.ts
- src/pages/PaymentDetails.tsx
- src/types/index.ts
Displays an "External Payment ID" on the payments page if one is valid. The id can be variable length depending on the org so we will displayed a shortened string for id's that are longer than 20 characters.
id longer than 20 chars
id less than 20 chars
no id
> [SDP-1024] Display external payment ID in Payment Details page

- CHANGELOG.md
- package.json
- src/components/RetryFailedPayment.tsx
- src/pages/PaymentDetails.tsx
- src/types/index.ts
The retry payment button was not showing up after #15.
The code was relying on the order of the entries in the status_history array. Status history is metadata, so it's not very reliable and we should rely on the status instead.
1. Pointed my FE to the dev instance (https://stellar-disbursement-platform-backend-dev.stellar.org)
2. Created a payment to my phone number
3. Registered a wallet using the demo wallet, but without creating the account
4. The payment failed with op_no_destination
5. I created the account and retried it
6. The payment failed with op_no_trust
7. I created the trustline and retried it
8. It succeeded 🎉
The payment used for this test is at https://stellar-disbursement-platform-frontend-dev.stellar.org/payments/b27db2ed-dd87-4127-b165-98f98c70144b
> [Hot-fix] Retry payment button was not showing up

- CHANGELOG.md
- package.json
- src/components/RetryFailedPayment.tsx
- src/pages/PaymentDetails.tsx
- src/types/index.ts
The retry payment button was not showing up after #15.
The code was relying on the order of the entries in the status_history array. Status history is metadata, so it's not very reliable and we should rely on the status instead.
1. Pointed my FE to the dev instance (https://stellar-disbursement-platform-backend-dev.stellar.org)
2. Created a payment to my phone number
3. Registered a wallet using the demo wallet, but without creating the account
4. The payment failed with op_no_destination
5. I created the account and retried it
6. The payment failed with op_no_trust
7. I created the trustline and retried it
8. It succeeded 🎉
The payment used for this test is at https://stellar-disbursement-platform-frontend-dev.stellar.org/payments/b27db2ed-dd87-4127-b165-98f98c70144b
> [Hot-fix] Retry payment button was not showing up (#72)

- src/apiQueries/useReceiversReceiverId.ts
- src/apiQueries/useUpdateReceiverDetails.ts
- src/helpers/formatReceiver.ts
- src/pages/ReceiverDetailsEdit.tsx
- src/types/index.ts
Now users can add/update the receivers' verification info. Only **NOT** confirmed verification can be updated.
> [SDP-899] feat: patch receivers' verification info

- src/api/getOrgLogo.ts
- src/store/ducks/organization.ts
Endpoint `GET /organization/logo` fails for multi-tenancy because the endpoint isn't authenticated and is not associated with a tenant. 
Adding authentication to `GET /organization/logo` solves this issue.
> SDP-1095 - [FE] getting 400 when calling GET `/organization/logo`

- src/helpers/formatIntlDateTime.ts
- src/pages/PaymentDetails.tsx
Payments are usually processed within one minute, which means the timestamps are not very meaningful. We should add seconds so a user can actually see the history and how the payment is processed on Stellar. ex: Mar 7, 2024, 12:57:06 PM
> [SDP-1138]: Add seconds to payment history in Payment Details

- src/api/patchOrgInfo.ts
- src/pages/Profile.tsx
- src/store/ducks/organization.ts
- src/types/index.ts
> [SDP-703]: Support the edition of the privacy_policy_link

- src/constants/envVariables.ts
- webpack.common.js
Make sure to only export the envs needed
FYI: I confirmed that with the new configuration, the envs behavior still the same: they're loaded from .env if available, otherwise they are loaded from window._env_
📈 Kaizen
> [SDP-1206] Make sure to only export the envs needed

- src/components/WalletCard/index.tsx
- src/pages/WalletProviders.tsx
Disable the wallet toggle for in the WalletProviders screen unless the user has the owner role.
> [SDP-1215] Disable the wallet toggle for in the WalletProviders screen unless the user has the owner role

- package.json
- yarn.lock
- Bump `webpack-dev-server`, which updates its webpack-dev-middleware dependency to 5.3.4, solving [CVE-2024-29180](https://github.com/advisories/GHSA-wr3j-pwj9-hqq6).
- Bump the `browserify-sign` indirect dependency to 4.2.3, solving [CVE-2023-46234](https://github.com/advisories/GHSA-x9w5-v3q2-3rhw).
- Bump the `@babel/traverse` indirect dependency to ^7.23.2, solving [CVE-2023-45133](https://github.com/advisories/GHSA-67hx-6x53-jw92).
- Bump `oidc-client-ts`, which updates its crypto-js dependency to 4.2.0, solving [CVE-2023-46233](https://github.com/advisories/GHSA-xwcq-pm8m-c4vf).
> Address CVEs

- src/components/SettingsTeamMembers.tsx
Display the user email on the "Team Members" section.
This is a piece of important user-related information when managing the organization's users.
> [SDP-1235] Display the user email on the "Team Members" section

- src/components/DashboardAnalytics.tsx
- src/helpers/formatDisbursements.ts
- src/helpers/formatStatistics.ts
- src/types/index.ts
When calculating the successful payments percentage, we need to remove draft payments count from the total payments count in the divisor.
for ex,
here, the `DRAFT` payment does not count towards the divisor, so the successful payment rate is 1/1 = 100%
here, a `READY` payment is added to the divisor, so the successful payment rate is 1/2 = 50%
> [Fix] Remove draft payments from remaining payments count when calculating % successful payments

- src/apiQueries/useCircleBalances.ts
- src/components/DisbursementDetails/index.tsx
Restricting selection of assets that have trustlines and balances during the disbursement upload process will prevent us from creating draft disbursements where payments cannot be started.
For native accounts,
with only native XLM
after adding trustline for USDC
after adding asset that's not whitelisted
for USDC Circle account
> [Fix] Do not allow selection of asset that does not have an account trustline / balance

- src/components/DisbursementDetails/index.tsx
Fix bug introduced in PR #134 where the upload csv button would never be enabled.
The bug was caused because the PR removed the `{renderDropdownDefault(isWalletAssetsFetching)}` line of code that inserts the (initial) "empty dropdown value" to the dropdown list, and it resulted in preventing the _dropdown selection changed_ event from being called when the assets dropdown list contained a single item. That mistake prevents disbursement instructions from being uploaded.
Update the syntax of the javascript filter function to return explicit booleans.
> [SDP-1323] Fix bug introduced in PR #134 where the upload csv button would never be enabled

- src/api/postDisbursement.ts
- src/apiQueries/useUpdateOrgSmsRetryInterval.ts
- src/apiQueries/useUpdateOrgSmsTemplate.ts
- src/helpers/formatDisbursements.ts
- src/store/ducks/organization.ts
- src/types/index.ts
Rename the following fields for `organization` and `disbursement` 
* `sms_resend_interval` -> `receiver_invitation_resend_interval_days` 
* `sms_registration_message_template` -> `receiver_registration_message_template` 
This change is required to match the breaking change introduced in this PR https://github.com/stellar/stellar-disbursement-platform-backend/pull/412
> [SDP-1316] Rename fields for receiver invitation template and interval

- package.json
- yarn.lock
Remove the `node-sass` dependency.
It cannot be built from ARM architecture, nor with node higher than `14.x`
Also, the project was successfully built for dev and production without ~`nods-sass`~, since `sass` is already in the project and is a replaced [recommended by node-sass](https://www.npmjs.com/package/node-sass):
> Chore: remove the `node-sass` dependency

- package.json
- src/apiQueries/useAssetsByWallet.ts
- src/components/DisbursementButtons/index.tsx
- src/components/DisbursementDetails/index.tsx
- src/types/index.ts
Setup inter-dependency between dropdowns in the NewDisbursement screen:
> [SDP-1369] Setup inter-dependency between dropdowns in the NewDisbursement screen

- src/helpers/formatReceiver.ts
Receiver verifications is an optional field after changes introduced in https://stellarorg.atlassian.net/browse/SDP-1222.
> [Fix] Make receiver verifications optional

- src/apiQueries/useWallets.ts
- src/components/DisbursementDetails/index.tsx
- src/pages/WalletProviders.tsx
- The Wallet Providers screen does not apply this query parameter and calls `GET /wallets` directly.
- The New Disbursement screen uses `GET /wallets?user_managed=false`
> Feat: Update GET /wallets with the `?user_managed={boolean}` query param

- src/components/PaymentsTable.tsx
- src/styles.scss
- Surface External Payment IDs on the payment listing page
- Increase size of payment ID column.
> [SDP-1525] Surface external payment IDs

- src/pages/Payments.tsx
Allow the user to submit a search query `q={term}` in the payments list. The backend will return results based on queries for `payments.id`, `payments.external_payment_id`, `payments.receiver_wallet.stellar_address`, `payments.disbursement.name`.
Address the BE part of https://stellarorg.atlassian.net/browse/SDP-1535
> SDP-1535: Allow the user to submit a search query `q={term}` in the payments list

- CHANGELOG.md
- src/apiQueries/useUpdateOrgShortLinkEnabled.ts
- src/components/SettingsEnableShortLinking.tsx
- src/pages/Settings.tsx
- src/store/ducks/organization.ts
- src/types/index.ts
Add option to enable short linking from the settings page.
- To reduce the cost of SMS messages.
- To have a more reliable experience (long links are scarry).
> [SDP-1528] Add option to enable short linking from the settings page

- src/apiQueries/useUpdateOrgMemoTrackingEnabled.ts
- src/components/SettingsEnableMemoTracking.tsx
- src/store/ducks/organization.ts
- src/types/index.ts
Rename variable `is_tenant_memo_enabled` to `is_memo_tracing_enabled`.
This was renamed in the backend and I forgot to rename it in the FE as well.
> Fix: rename variable `is_tenant_memo_enabled` to `is_memo_tracing_enabled`

- CHANGELOG.md
- src/pages/ForgotPassword.tsx
- src/pages/ResetPassword.tsx
Improve UX on the fogotPassword->resetPassword flow:
- The reset-password page now parses a query parameter from the URL: `?token={confirmation-token}`
- Since the reset token is parsed from the URL, we don't need the token field anymore.
> [SDP-1496] Improve UX on the fogotPassword->resetPassword flow

- CHANGELOG.md
- src/api/postDisbursement.ts
- src/api/postDisbursementWithInstructions.ts
- src/store/ducks/disbursementDrafts.ts
* Added `postDisbursementWithInstructions` function in `src/api/postDisbursementWithInstructions.ts` to handle disbursements with instructions and file uploads in a single atomic API call.
Matching backend change : https://github.com/stellar/stellar-disbursement-platform-backend/pull/554
> [SDP-1549] Make `Confirm Disbursement` atomic

- README.md
Change example api to use `http` instead of `https`
This is causing `Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR` if directly copy paste
> [Fix] Fix readme env example

- CHANGELOG.md
- src/components/ReceiverWalletBalance.tsx
- src/types/index.ts
If a receiver only has `XLM` balance, the balance field will show `-`. This is because the native asset does not have `asset_code` or `asset_issuer`. 
We want to show asset balances.
N/A
> SDP-1649: Fix receiver's XLM balance

- package.json
- src/apiQueries/useAccountBalances.ts
- src/apiQueries/useStellarAccountInfo.ts
- src/components/ReceiverWalletBalance.tsx
- src/constants/envVariables.ts
- src/pages/ReceiverDetails.tsx
- src/types/index.ts
- yarn.lock
When a receiver's contract account wallet is selected:
- Balances of assets registered with SDP will have their balances fetched. This feature requires RPC integration; if the `RPC_URL` configuration is not set, then the balance will show "Unavailable".
- Recent wallet history is disabled
This change also filters out any assets with a 0 balance from the balances field for G-addresses. This is done for consistency with contract accounts. Contract accounts do not have a concept of a trustline, and therefore, we cannot distinguish a 0 balance from never receiving a balance.
The receiver page does not work when a contract account wallet is selected.
N/A
> SDP-1610: Update receivers page for contract accounts

- CHANGELOG.md
- src/apiQueries/useUpdateReceiverWalletStatus.ts
- src/pages/ReceiverDetails.tsx
- Add a button to unregister a receiver wallet. 
- Force receiver to go through verification again and re-register a wallet. Useful in case the receiver changed wallets.
> SDP-1486: Unregister Receiver Wallet

- src/apiQueries/useUpdateOrgHTMLEmailTemplate.ts
- src/components/ReceiverInviteHTMLEmailTemplate/index.tsx
- src/components/ReceiverInviteHTMLEmailTemplate/styles.scss
- src/pages/Settings.tsx
- src/store/ducks/organization.ts
- src/types/index.ts
This adds a setting for custom HTML email disbursement invites.
We need to support custom HTML/CSS emails for the demo.
N/A
> SDP-1736: Allow org level HTML customization of invite

- CHANGELOG.md
- src/App.tsx
- src/components/DisbursementButtons/index.tsx
- src/components/DisbursementInstructions/index.tsx
- src/components/NewDisbursementButton.tsx
- src/constants/settings.ts
- src/helpers/userRoleText.ts
- src/pages/DisbursementDraftDetails.tsx
- src/pages/Disbursements.tsx
- src/pages/Home.tsx
- src/pages/Payments.tsx
- src/store/ducks/disbursementDrafts.ts
- src/types/index.ts
- Implemented initiator and approver roles with separated disbursement operations. Initiators can create and save drafts but cannot confirm disbursements, while approvers can confirm clean drafts but cannot save changes. 
- Added form state tracking to disable confirmation when drafts have unsaved modifications. This allows to separate saving the disbursement from confirming it to be able to assign different roles to different operations. 
- The platform needed role separation for compliance and workflow control, where different users handle disbursement creation vs approval.
> SDP-1843: Add initiator and approver roles
