stellar/stellar-disbursement-platform-frontend

- src/App.tsx
- src/api/patchReceiver.ts
- src/constants/settings.ts
- src/generated/gitInfo.ts
- src/pages/ReceiverDetails.tsx
- src/pages/ReceiverDetailsEdit.tsx
- src/store/ducks/receiverDetails.ts
- src/types/index.ts
`Edit receiver` page. Email and External ID only
> SDP-831: Edit receivers

- src/App.tsx
- src/api/patchProfilePassword.ts
- src/constants/settings.ts
- src/generated/gitInfo.ts
- src/helpers/validateNewPassword.ts
- src/helpers/validatePasswordMatch.ts
- src/pages/Profile.tsx
- src/pages/ResetPassword.tsx
- src/pages/SetNewPassword.tsx
- src/store/ducks/forgotPassword.ts
- src/types/index.ts
Separated password flow from forgot password, for the case the user is logged in and wants to reset password.
> SDP-829: Set pw flow instead of forgot pw

- src/generated/gitInfo.ts
- src/pages/Wallets.tsx
> Wallets: add message about distribution account funds

- src/components/MultipleAmounts/index.tsx
> Fix receiver no amount typo

- src/api/retryInvitationSMS.ts
- src/generated/gitInfo.ts
- src/pages/ReceiverDetails.tsx
- src/store/ducks/receiverDetails.ts
- src/styles.scss
- src/types/index.ts
Added a way to re-send invitation SMS messages to users from the front end.
BE ready (SDP-262)
> SDP-877: Retry invitation SMS

- src/apiQueries/useUpdateOrgSmsTemplate.ts
- src/components/ReceiverInviteMessage/index.tsx
- src/components/ReceiverInviteMessage/styles.scss
- src/helpers/fetchApi.ts
- src/pages/Settings.tsx
- src/store/ducks/organization.ts
- src/types/index.ts
> SDP-769: Receiver invite message UI

- src/apiQueries/useUpdateOrgSmsRetryInterval.ts
- src/components/SettingsEnableSmsRetry.tsx
- src/pages/Settings.tsx
- src/store/ducks/organization.ts
- src/styles.scss
- src/types/index.ts
Will add info text when ready.
> SDP-929: Settings - enable SMS retry interval

- src/components/DashboardAnalytics.tsx
> Analytics cards: adjust layout

- .github/workflows/docker_image_public_release.yml
- src/api/getDisbursementDetails.ts
- src/api/getDisbursementDrafts.ts
- src/api/getDisbursementInstructions.ts
- src/api/getDisbursementReceivers.ts
- src/api/getDisbursements.ts
- src/api/getOrgInfo.ts
- src/api/getProfileInfo.ts
- src/api/patchDisbursementStatus.ts
- src/api/patchOrgInfo.ts
- src/api/patchProfileInfo.ts
- src/api/patchUserRole.ts
- src/api/postDisbursement.ts
- src/api/postDisbursementFile.ts
- src/api/refreshToken.ts
- src/helpers/fetchApi.ts
- src/pages/MFAuth.tsx
- src/pages/SignIn.tsx
Replace the header name to `SDP-Tenant-Name` as that's what we're expecting at the backend.
> chore: Replace multi-tenant header name.

- src/api/handleApiErrorString.ts
- src/helpers/normalizeApiError.ts
> [SDP-976] Sign in: show error details

- package.json
- yarn.lock
Fixes https://github.com/stellar/stellar-disbursement-platform-backend/issues/120
> Update SDS package

- src/App.tsx
> [SDP-1011] business user role should receive permission to view details for individual payments, details, and receivers

- public/resources/disbursement-template.csv
Ticket : https://stellarorg.atlassian.net/browse/SDP-1099 
Add missing external payment id to disbursement instructions csv template
> [SDP-1099] add external payment id to disbursement instructions

- .github/ISSUE_TEMPLATE/release_a_new_version.md
- CHANGELOG.md
- package.json
> Release 2.0.0-rc1

- .github/workflows/test-build.yml
- CHANGELOG.md
- package.json
- Add Changelog
- Update the hardcoded version
- Update the the helm charts
> Release `2.1.0-rc.1` to `develop`

- src/components/NewDisbursementButton.tsx
- src/helpers/formatPaymentDetails.ts
- src/pages/Home.tsx
- src/pages/PaymentDetails.tsx
- src/types/index.ts
- Payment details: Conditionally show Circle Transfer ID field
- Disable "New Disbursement" button if Circle Account is not active
> Circle payout updates

- src/apiQueries/useUpdateReceiverDetails.ts
- src/components/DisbursementDetails/index.tsx
- src/pages/ReceiverDetailsEdit.tsx
- src/types/index.ts
> [SDP-1282] Support the new verification type `YEAR_MONTH`

- README.md
- public/settings/env-config.js
- src/constants/envVariables.ts
- src/pages/ForgotPassword.tsx
- src/pages/MFAuth.tsx
- src/pages/ResetPassword.tsx
- src/pages/SignIn.tsx
- webpack.common.js
these occur when `SINGLE_TENANT_MODE: true`
login screen
forgot password 
reset password
> Disable "Org Name" input when in single-tnt mode

- public/resources/disbursement-template.csv
Add email column to the CSV template.
Addresses https://stellarorg.atlassian.net/browse/SDP-1310.
> [SDP-1310] Add email column to the CSV template

- src/pages/DisbursementsNew.tsx
Fix code that relied on CSV column order
This is an unreasonable assumption.
Here's the main change: https://github.com/stellar/stellar-disbursement-platform-frontend/commit/594eb850e7d294ea17c250879717feeb87feaf40
The other commit is a small refactor that doesn't change the main logic.
> [SDP-1325] fix code that relied on CSV column order

- src/api/postDisbursement.ts
- src/apiQueries/useUpdateOrgInvitationRetryInterval.ts
- src/components/DisbursementDetails/index.tsx
- src/components/DisbursementInviteMessage/index.tsx
- src/components/ReceiverInviteMessage/index.tsx
- src/components/SettingsEnableReceiverInvitationRetry.tsx
- src/helpers/formatDisbursements.ts
- src/pages/DisbursementDetails.tsx
- src/pages/DisbursementDraftDetails.tsx
- src/pages/DisbursementsNew.tsx
- src/pages/ReceiverDetails.tsx
- src/pages/Settings.tsx
- src/store/ducks/disbursementDetails.ts
- src/store/ducks/organization.ts
- src/types/index.ts
* Update SMS retry messaging to be agnostic of channel 
* Cleanup variable names to remove SMS mentions.
> SDP-1333 Update Organization SMS Retry configuration to reflect both Email and SMS

- CHANGELOG.md
- package.json
> Update changelog and bump version for 3.0.0-rc.1

- src/App.tsx
- src/api/refreshToken.ts
- src/components/SessionTicker.tsx
- src/components/SessionTokenRefresher.tsx
Add a TokenSessionRefresher component to prevent the session from expiring so often when the page is open.
Address https://stellarorg.atlassian.net/browse/SDP-1355
> [SDP-1355] Add a TokenSessionRefresher component to prevent the session from expiring so often when the page is open

- src/apiQueries/useUpdateReceiverDetails.ts
- src/components/ReceiversTable.tsx
- src/pages/ReceiverDetailsEdit.tsx
- src/types/index.ts
Allow receivers' phone numbers to be patched.
Address https://stellarorg.atlassian.net/browse/SDP-1303
> [SDP-1303] PATCH receiver's phone number

- src/components/DashboardAnalytics.tsx
- src/pages/ReceiverDetails.tsx
Fix the checks enforced when calculating the success payments percentage
Address https://stellarorg.atlassian.net/browse/SDP-1353
> [SDP-1353] fix the checks enforced when calculating the success payments percentage

- src/api/getDisbursementsExport.ts
- src/pages/Disbursements.tsx
- src/store/ducks/disbursements.ts
* Implement Export functionality for Disbursements page.
> [SDP-1451] Export Disbursements

- src/api/getExport.ts
- src/pages/Disbursements.tsx
- src/pages/Payments.tsx
- src/pages/Receivers.tsx
- src/store/ducks/dataExport.ts
- src/store/ducks/disbursements.ts
- src/types/index.ts
- Consolidate all export functionality in `dataExport.ts` and `getExport.ts` 
- Implement Export functionality for Receivers and Payments.
> [SDP-1451] Export Receivers and Payments

- src/api/deleteDisbursementDraft.ts
- src/pages/DisbursementDraftDetails.tsx
- src/store/ducks/disbursementDrafts.ts
- src/types/index.ts
Add a button to allow deleting Draft Disbursements.
> [SDP-1453] Delete Draft Disbursement

- README.md
- src/constants/envVariables.ts
- src/constants/settings.ts
- src/helpers/getSdpTenantName.ts
- src/helpers/localStorageTenantName.ts
- src/pages/SignIn.tsx
- webpack.common.js
Ticket: https://stellarorg.atlassian.net/browse/SDP-1341
> [SDP-1341] Disable prefilling tenant name from domain

- package.json
- yarn.lock
https://github.com/stellar/stellar-disbursement-platform-frontend/security/dependabot/37
> Bump webpack-dev

- .github/workflows/automated_release_process.yml
- .github/workflows/templates/release-issue.md
- .github/workflows/templates/release-pr-dev.md
- .github/workflows/templates/release-pr-main.md
https://github.com/user-attachments/assets/d9a94462-36b9-47f7-bde7-8b9d2da1a4e6
- https://github.com/marcelosalloum/stellar-disbursement-platform-frontend/pull/11
- https://github.com/marcelosalloum/stellar-disbursement-platform-frontend/pull/12
- [**DRAFT** Release](https://github.com/marcelosalloum/stellar-disbursement-platform-frontend/releases/tag/untagged-589a893bccb40b079dcd)
- https://github.com/marcelosalloum/stellar-disbursement-platform-frontend/issues/13
> [SDP-1542] Automate the Release Process 🤖

- src/apiQueries/useUpdateOrgMemoTrackingEnabled.ts
- src/components/SettingsEnableMemoTracking.tsx
- src/pages/Settings.tsx
- src/store/ducks/organization.ts
- src/types/index.ts
> [SDP-1544] Allow users to toggle memo tracking

- CHANGELOG.md
- src/pages/ForgotPassword.tsx
- src/pages/ResetPassword.tsx
- src/pages/SignIn.tsx
After the user successfully resets their password, they're now redirected to the SignIn screen, and a success message is displayed once there:
https://github.com/user-attachments/assets/fb24cc4d-2dab-4d63-8dbb-4b6dda870754
Address https://stellarorg.atlassian.net/browse/SDP-1497
> [SDP-1497] Reset password redirect

- .github/pull_request_template.md
- package.json
Add PR template.
Code quality.
> Chore: Add PR template

- CHANGELOG.md
- public/resources/disbursementTemplates/EMAIL_AND_WALLET_ADDRESS.csv
- public/resources/disbursementTemplates/PHONE_NUMBER_AND_WALLET_ADDRESS.csv
- src/helpers/formatReceiver.ts
- src/pages/ReceiverDetails.tsx
- src/types/index.ts
Update CSV examples with memo columns and include the memo in the receiver detail screen.
Address https://stellarorg.atlassian.net/browse/SDP-1480.
> [SDP-1480] Update CSV examples with memo columns

- CHANGELOG.md
- src/components/SettingsEnableShortLinking.tsx
Change ID of short-linking toggle.
Enabling automatic payment cancellation enables short linking instead.
> SDP-1648: Fix Payment cancellation toggle

- CHANGELOG.md
- package.json
- src/components/SettingsEnableShortLinking.tsx
- yarn.lock
Merge `develop` into `feature/c-accounts`
Keeping feature branch in sync.
N/A
> Chore: Merge `develop` into `feature/c-accounts`

- package.json
- yarn.lock
Update the dependencies versions
We want to address dependabot security issues
[TODO or N/A]
> SDP-1705 update dependencies

- src/components/DirectPaymentCreateModal/styles.scss
https://github.com/user-attachments/assets/b6e5be58-e666-4823-bdfa-d1a95a71118f
[TODO: Why this change is being made. Include any context required to understand the why.]
[TODO or N/A]
> fix direct payment overflow

- src/components/BridgeIntegrationSection/index.tsx
- src/components/DistributionAccountStellar.tsx
Fix text size on the Distribution Account page.
Text was too small.
[TODO or N/A]
> Distribution Account: fix text size

- src/helpers/validateVerificationFields.ts
- vite.config.ts
- Fix `Create Receiver` birthdate validation. 
- Change vite configs 
- Create Receiver date validation shows the wrong date due to UTC time conversion.
> SDP-1814 - Create receiver date validation & Vite configs for local dev.

- .gitignore
- src/api/getDisbursements.ts
- src/apiQueries/usePayments.ts
- src/apiQueries/useReceivers.ts
- src/helpers/normalizeApiError.ts
Using immutable data handling in React Query.
Trying to address the random data undefined error that keeps popping up.
[TODO or N/A]
> SDP-1464: Immutable data handling in React Query
